volumes:
  database_data_dev:
  app_dev_node_modules:

services:
  app-dev:
    build:
      context: ./services/web
      target: development
    volumes:
      - ./services/web/:/app/
      - app_dev_node_modules:/app/node_modules
    env_file:
      - ./services/web/.env
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - database-dev

  database-dev:
    image: postgres:16-alpine
    volumes:
      - database_data_dev:/var/lib/postgresql/data
    env_file:
      - ./services/database/.env
    ports:
      - 5432:5432
