volumes:
  database_data:
  storage_data:

services:
  app:
    image: pixelgrid/app:latest
    build:
      context: ./services/web
      target: production
    env_file:
      - ./services/web/.env
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - ./services/database/.env
    ports:
      - 5432:5432

  storage:
    image: pixelgrid/storage:latest
    build: ./services/storage
    env_file:
      - ./services/storage/.env
    volumes:
      - storage_data:/data
    ports:
      - 9000:9000
      - 9001:9001
