volumes:
  database_data_dev:
  storage_data_dev:
  broker_data_dev:

networks:
  storage_net_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 180.24.0.0/16
          gateway: 180.24.0.1

services:
  app-dev:
    build:
      context: ./services/web
      target: web-development
    env_file:
      - ./services/web/.env
    environment:
      - STORAGE_S3_ENDPOINT=http://180.24.0.2:9000
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      default:
      storage_net_dev:
        ipv4_address: 180.24.0.3
    depends_on:
      database-dev:
        condition: service_started
      storage-dev:
        condition: service_healthy
      broker-dev:
        condition: service_healthy
        restart: true
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./services/web/
          target: /app
          ignore:
            - node_modules/

        - action: rebuild
          path: ./services/web/package.json

  app-classifier-dev:
    build:
      context: ./services/web
      target: classifier-development
    env_file:
      - ./services/web/.env
    environment:
      - STORAGE_S3_ENDPOINT=http://180.24.0.2:9000
    networks:
      default:
      storage_net_dev:
        ipv4_address: 180.24.0.4
    depends_on:
      database-dev:
        condition: service_started
      storage-dev:
        condition: service_healthy
      broker-dev:
        condition: service_healthy
        restart: true
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./services/web/
          target: /app
          ignore:
            - node_modules/

        - action: rebuild
          path: ./services/web/package.json

  database-dev:
    image: postgres:16-alpine
    volumes:
      - database_data_dev:/var/lib/postgresql/data
    env_file:
      - ./services/database/.env
    ports:
      - 5432:5432

  storage-dev:
    build: ./services/storage
    env_file:
      - ./services/storage/.env
    volumes:
      - storage_data_dev:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      storage_net_dev:
        ipv4_address: 180.24.0.2

  broker-dev:
    build: ./services/broker
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - ./services/broker/.env
    volumes:
      - broker_data_dev:/var/lib/rabbitmq/
