volumes:
  database_data_dev:

services:
  app-dev:
    build:
      context: ./services/web
      target: development
    volumes:
      - ./services/web:/app
      - /app/node_modules
    env_file:
      - ./services/web/.env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@database-dev:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    ports:
      - 3000:3000
    depends_on:
      - database-dev

  database-dev:
    image: postgres:16-alpine
    volumes:
      - database_data_dev:/var/lib/postgresql/data
    env_file:
      - ./services/web/.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
